name: caching and artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-cache-${{ hashFiles('**/package-lock.json') }} # npm-cache-7383493
          restore-keys: |
            ${{runner.os}}-npm-cache-
            ${{runner.os}}-
      - name: display cache output
        run: echo '${{ toJson(steps.cache-dependencies.outputs) }}'
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
      - name: upload code coverage report
        uses: actions/upload-artifact@v3
        if: always() # to always run if test fail
        with:
          name: code-coverage
          path: coverage
          retention-days: 10
      - name: use axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', {headers: {Accept: 'text/plain'}})
            console.log(res.data)
