name: checkout
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -al
      - uses: action/checkout@v3
      - name: list files after
        run: ls -al

  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -a
      - name: checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/weihan1394/github-actions"
          git fetch origin
          git checkout main
      - name: list files after
        run: ls -al
