name: respository events
# on: [push, pull_request, issues]
on:
  push:
    branches:
      - main
      - "feature/*"
      - "feature/**"
      - develop
    paths:
      - "**.js"
  # pull_request:
  #   types: [opened, assigned, reopened, synchronize]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3
