name: First workflow
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline command
        run: |
          node -v
          npm -v

  parallel-job:
    runs-on: ubuntu-latest
    needs: [run-shell-command]
    steps:
      - name: check version
        run: cat /etc/os-release

  dependant-job:
    runs-on: ubuntu-latest
    needs: [run-shell-command]
    steps:
      - name: echo a string
        run: echo "hello"
      - name: error step
        run: doesnotexis
