name: matrix
on: [push]

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
    runs-on: ${{matrix.os}}
    steps:
      - run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - run: node -v
