name: matrix
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 15, 16]
    steps:
      - run: node -v
      - uses: actions/setup-node
        with:
          node-version: ${{matrix.node-version}}
      - run: node -v
