name: status check functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: sleep 20
      - name: runs on failure
        if: failure()
        run: echo 'runs on failure'
      - name: runs on success
        run: echo 'runs on success'
      - name: always run
        if: always()
        run: echo 'Always Runs'
      - name: runs when cancelled
        if: cancelled()
        run: echo 'runs on cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
