name: working dirs & shells
on: [push]
defaults:
  run:
    shell: bash

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: display working direction and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: change working dir
        working-directory: /home/runner
        run: |
          pwd

  display-wd-info-widndows:
    runs-on: ubuntu-latest
    steps:
      - name: display working  direction and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: run python shell
        shell: python
        run: |
          print("hello")
